### PR TITLE
Fix install from git

### PR DESCRIPTION
**Pull request by knopki**
This PR fixes installation from git is broken (`pip install git+https://github...`). Related failed build https://github.com/tilde-lab/aiida-crystal-dft/actions/runs/3522788732/jobs/5906177063

Unknown key `project.optional_dependecies` in `pyproject.toml` - should be `project.optional-dependencies` ([reference](https://flit.pypa.io/en/stable/pyproject_toml.html#dependencies))

`tool.flit.module.name` should be the name of the module directory ([reference](https://flit.pypa.io/en/stable/pyproject_toml.html#module-section))

### CODE REVIEW

**Comment by knopki** [comment]
The CI job is fixed to the ''Test with pytest'' step. `pytest' is more broken than I can understand.

**Comment by ansobolev** [comment]
You've got to add `aiida-testing-dev` to `project.optional_dependencies[testing]` in `pyproject.toml`

**Comment by knopki** [comment]
@ansobolev Thanks, but it looks like it's not enough:
```
Traceback (most recent call last):
  File "/home/aiida/.local/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 179, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/__init__.py", line 214, in <lambda>
    hook.multicall(
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 612, in pytest_cmdline_parse
    self.parse(args)
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 777, in parse
    self._preparse(args, addopts=addopts)
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 729, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/aiida/.local/lib/python3.8/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/conda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/opt/conda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/aiida/.local/lib/python3.8/site-packages/aiida_testing/mock_code/__init__.py", line 8, in <module>
    from ._fixtures import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/home/aiida/.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/aiida/.local/lib/python3.8/site-packages/aiida_testing/mock_code/_fixtures.py", line 95, in <module>
    mock_fail_on_missing, request: pytest.FixtureRequest, tmp_path: pathlib.Path
AttributeError: module 'pytest' has no attribute 'FixtureRequest'
```
Top-level export of `FixtureRequest` was introduced in `pytest==6.2.0` (https://github.com/pytest-dev/pytest/commit/f1e6fdcddbfe8991935685ccc5049dd957ec4382), we have `3.6.3`. But with `pytest>=6.2.0` a lot of errors appear in the tests. This is too much for me :)

**Comment by ansobolev** [comment]
I pushed a commit that fixes all the tests but 4. These 4 tests deal with the binary files parsing, and are failing due to aiida changing its way of storing files in a repo in v2.x. It'll need a little deeper refactoring, I'll do that as soon as I have time. However, as the binary files are dealt with only in `properties` calculations, and we don't do them, they can be skipped in the meantime.

**Comment by knopki** [comment]
@ansobolev Thanks! I rebased branch against master. With `aiida-testing-dev` and `pytest>=6.2.0` it's only 10 failed test (not sure why not 4). If that is enough, I would like to merge this PR. The original goal was to fix the installation of `mpds-aiida` and `metis-backend`.

**Review by blokhin — APPROVED** [review]

**Pull request merged**
